spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${AUTH_DB_HOST:localhost}:${AUTH_DB_PORT:5432}/${AUTH_DB_SCHEMA:postgres}?currentSchema=${AUTH_DB_INNER_SCHEMA:crud}
    username: ${AUTH_DB_USER:postgres}
    password: ${AUTH_DB_PASSWORD:admin}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: none
    show-sql: true